# Generated by Django 3.2.10 on 2021-12-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='avalicao',
            new_name='avaliacao',
        ),
    ]
