# Generated by Django 3.2.10 on 2021-12-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_rename_avalicao_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ('id',), 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ('id',), 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
